# Generated by Django 4.1.3 on 2022-11-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='banner_title',
            field=models.CharField(default='News page', max_length=100),
        ),
    ]
