# Generated by Django 4.1.3 on 2022-11-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('news', '0002_newspage_introduction_alter_newspage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='banner_image',
            field=models.ForeignKey(blank='False', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
