# Generated by Django 4.1.3 on 2022-11-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articleauthor_articleauthororderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauthor',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
