# Generated by Django 4.1.3 on 2022-11-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articleauthor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
