# Generated by Django 4.1.3 on 2022-11-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_articlepage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='subtitle',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
