# Generated by Django 4.1.3 on 2022-11-17 02:35

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_newspage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='article_body',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Add additional text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.SimpleRichTextBlock())], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Add additional text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.SimpleRichTextBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
