# Generated by Django 4.1.3 on 2022-11-17 02:42

from django.db import migrations
import streams.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_articlepage_article_body_articlepage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
