# Generated by Django 4.1.3 on 2022-11-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articleauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleauthor',
            options={'verbose_name': 'Article Author', 'verbose_name_plural': 'Article Authors'},
        ),
    ]
