# Generated by Django 4.1.3 on 2022-11-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_articleauthor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
    ]
